server:
  port: 9192
spring:
  application:
    name: hystrix-dashboard

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: true
    fetch-registry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

  instance:
    appname: hystrix-dashboard
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"