# application name
spring:
  application:
    name: USER-SERVICE

#h2 config
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

# jpa config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

# server port change

server:
  port: 8081

# cloud config

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: true
    fetch-registry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

  instance:
    appname: USER-SERVICE