spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect


server:
  port: 8082



eureka:
  instance:
    appname: DEPARTMENT-SERVICE
  client:
    register-with-eureka: true
    fetch-registry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

  server:
      enableSelfPreservation: false
